name: Docker Image CI

on:
  schedule:
  - cron: "0 22 * * 0"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Canister Registry
        uses: docker/login-action@v2
        with:
          registry: cloud.canister.io:5000
          username: ${{ secrets.CANISTER_USERNAME }}
          password: ${{ secrets.CANISTER_PASSWORD }}
      - name: pull image
        run: docker pull nextcloud:fpm
      - name: get version
        id: version
        run: echo "VERSION=$(docker inspect image $(docker image ls | grep "nextcloud           fpm" | cut -c 39-51) 2>/dev/null | grep -m1 -oP '(?<="NEXTCLOUD_VERSION=)[^"]+')" >> $GITHUB_OUTPUT  
      - name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./
          push: true
          tags: |
             cpatscheider/nextcloud:latest 
             cpatscheider/nextcloud:fpm
             cpatscheider/nextcloud:${{steps.version.outputs.VERSION}}
             cloud.canister.io:5000/cpatscheider/nextcloud:latest 
             cloud.canister.io:5000/cpatscheider/nextcloud:fpm
             cloud.canister.io:5000/cpatscheider/nextcloud:${{steps.version.outputs.VERSION}}
          platforms: linux/amd64,linux/arm64
